### PR TITLE
[MRG] 4f to 3f corrections

### PR DESCRIPTION
**Pull request by HolterPhylo**

### CODE REVIEW

**Comment by monkeyman192** [comment]
this PR now contains multiple different things! You really want to keep things separate if possible. Like, have the Vector4f -> Vector3f changes in one PR, and the class changes for the update in a different, because now it's not easy to know what changes are due to what thing... Makes it much harder to review

**Comment by HolterPhylo** [comment]
Sorry about that, I will in the future.
For me, they show as individual commits that I can click and review as if they were separate.
But I understand it could be difficult to find the culprit if a problem happens.

**Comment by monkeyman192** [comment]
Yeah, they are separate commits, but a PR is meant to be a single change relating to one thing, which is composed of potentially multiple commits all relating to the same thing.

**Comment by HolterPhylo** [comment]
I'll try to stick to that in the future.  I understand.
I was just wrongly thinking that you had told me some time ago not to make so many PRs one after the other from Development.  You would have like that I made 3 PRs in this case?

**Pull request merged**
