### PR TITLE
Update to exe

### LINKED ISSUE #334: Add the option to not add the "File created using MBINCompiler version (X.XX.X)" line
**Is your feature request related to a problem? Please describe.**

I use git to track changes to the decompiled EXML files. Every time I do a conversion from MBIN to EXML using a new version of MBINCompiler, now all the files have diffs because the version number changes `<--File created using MBINCompiler version (3.42.0)-->` So then I have to do a global search-and-replace to remove this line.

**Describe the solution you'd like**

Ideally MBINCompiler would simply not add this version line, since it's totally not needed. However if we must have it added, then please allow the option not to add this line when decompiling MBINs. Thanks!

**Describe alternatives you've considered**

The workaround I've been using is to simply 

**Additional context**

### LINKED ISSUE #444: Log file information lacking a reference to the file and path that caused the log entry
Using v3.82.0-pre2

**Is your feature request related to a problem? Please describe.**
- In certain conditions, the Log file information is lacking a reference to the file and path that caused the log entry.
In this case, EXML files (MBIN files could also suffer from this lack of info, did not verify)

**Describe the solution you'd like**
- Every log entry of any type (normal, WARNING or ERROR) should referenced the involved filename and path like this:
[INFO]: D:\AMUMSS\MODBUILDER\MOD\METADATA\REALITY\TABLES\NMS_REALITY_GCPRODUCTTABLE.EXML

**Describe alternatives you've considered**
- Otherwise, the log info is only meaningful when converting ONE file at the time (because the file involved is known).
In bulk operation, the log info becomes impossible to related to a file in particular when many are processed

**Additional context**
- It looks like all Logger.Log... calls, outside of class MBINCompiler, do not have access to the filename and path of the current file being converted, so they cannot reference it in the log file.
If only Logger was aware of the filename and path currently processed...

Example log file output:
image

- These particular log messages are generated in libMBIN.BinaryStreamExtensions.WriteString but do not show which file or files caused them.
It should be able to do as MBINCompiler.Commands.Convert.WarnBroken does with 
     Logger.LogMessage( null, "INFO", $"{CommandLine.GetFileInfo( mbin )}" );

**Mitigating information**
If we just print the filename and path as each file is about to be processed (as cmkushnir comments below):
- The problem looks worst when multiple-threads are used (that is the default usage)
- If multiple-threads are NOT allowed, the log file content makes more sense as the information is at least sequential.

### LINKED ISSUE #445: Cannot invoke/change '--exclude=[;...]' behavior in a command line
**Describe the bug**
- Cannot use '--exclude=<Glob Pattern>[;<Glob Pattern>...]' as before in a batch file
and 'The default is --exclude="LANGUAGE\*;*.GEOMETRY.*".' prevents files in the LANGUAGE folder to be processed

**Expected behavior**
- '--exclude=";"' (previously working behavior) or '--exclude=""' should work to remove all restrictions

**Steps To Reproduce**
- extract the attached .zip file and execute Test.bat

**Specs (please complete the following information, if applicable):**
- Using MBINCompiler v3.82.0-pre2

**Additional Information**
- execute Test.bat from the attached .zip file

_Attachments:_
[Test.zip](https://github.com/monkeyman192/MBINCompiler/files/8334584/Test.zip)

### PR DESCRIPTION
**Pull request by HolterPhylo**
Added reference to file/path in log file. Closes #444
Added options:
--EXMLtoConsole: Enable sending EXML to Console (allows catching EXML instead of writing to disk)
--hideVersionInfo: Hide version info in EXML header. Closes #334
Corrected --exclude behavior. Closes #445

### CODE REVIEW

**Comment by monkeyman192** [comment]
Looks good. My one issue is that it might be nice to have the command line args be a bit simpler names? So maybe `--stream` instead of `--EXMLtoConsole`, and `--noversion` instead of `--hideVersionInfo`?
Also, if we have it as `stream`, then we could potentially allow it to output mbins this way too so that the process can be piped into other things.

**Comment by HolterPhylo** [comment]
I will change the names.
I’ll do the MBIN one later, I would like to have this before the next NMS
drop and don’t have time at the moment

**Comment by monkeyman192** [comment]
> I will change the names. I’ll do the MBIN one later, I would like to have this before the next NMS drop and don’t have time at the moment

Ok sounds good. not saying we need to have it work for mbin right now, but just saying if we keep the term generic then we can extend it in the future 😄

**Comment by monkeyman192** [comment]
Ok, looks good. I had one more question... What happens if you use `--stream` and ask it to do a whole directory/multiple files? I assume it will do all the files out through stdout?

**Comment by HolterPhylo** [comment]
It does it all.

**Comment by HolterPhylo** [comment]
like it would normally

**Comment by monkeyman192** [comment]
So really this `--stream` option will only make sense for single files?

**Comment by HolterPhylo** [comment]
Single and multiple files, just need to parse the output to retrieve each EXML.
Very easy to do AND much faster than writing/reading to disk for the same result!
I'll DM you an example output from lua...

**Pull request merged**
