### PR TITLE
Remove Size class attribute and enhance SizeOf method

### LINKED ISSUE #496: Remove `Size` Attribute from all classes
As it is quite annoying without doing a second pass over the entire data set and then determining the size recursively as part of the automation process, I think it would be better to instead just improve the `SizeOf` method of `NMSTemplate` so that it determines the size when requested, rather than having this information hard-coded in the class definition.
For the most part this field isn't actually used other than when determining the offset of a field, however this may be able to be cached so that only initial lookups are slow and subsequent ones are faster.

### PR DESCRIPTION
**Pull request by monkeyman192**
closes #496 

This removes the `Size` attribute from classes.
If the size of a class is needed, the `SizeOf` method should instead be used (eg. by `NMSTemplate.SizeOf(GcMessageProjectileImpact)`

I have also removed the `broken` attribute from a number of classes (there will be none now), as well as removing the atlas related classes from the projitems file which are no longer used.

### CODE REVIEW

**Comment by cmkushnir** [comment]
In NMSTemplate you add a check if type is String, and use Size attr value for field size if it is.  I expect this is correct for in-line string fields (stored as fixed size char[] in object) but not sure about VariableSizeString fields which are likely a fixed size of 32 bytes or something (ref wrapper to allocated string).
There will need to be a way for users to know that a string field is variable or fixed e.g. if using size to validate user entered string length.
A hack would be to use a negative size to indicate refs to allocated fields, or can add another bool attr Ref, or can add another RefSize attr.

**Comment by monkeyman192** [comment]
> In NMSTemplate you add a check if type is String, and use Size attr value for field size if it is. I expect this is correct for in-line string fields (stored as fixed size char[] in object) but not sure about VariableSizeString fields which are likely a fixed size of 32 bytes or something (ref wrapper to allocated string).

I don't exactly understand what you mean. I added the size check because otherwise the size of the string objects doesn't get added correctly. Also, once we have made the changes to move the NMSString0x... classes to use the string system class this will be even more important.
As you say, the variable sized strings have a fixed length (ie. 0x10 long as they look like a list essentially)... Now that I think about it variable length strings are really just `List<byte>`'s haha.

> There will need to be a way for users to know that a string field is variable or fixed e.g. if using size to validate user entered string length. A hack would be to use a negative size to indicate refs to allocated fields, or can add another bool attr Ref, or can add another RefSize attr.

Why do we need to do this? I am not clear on what you mean here sorry...

**Comment by cmkushnir** [comment]
What Size attr value will VariableSizeString fields have once converted to string ?  My assumption is they will be the size of the ref|pointer i.e. 0x10.  I assume they are not stored in-line like fixed length strings, maybe I 'm wrong.

If you do set the Size to the size of the ref|pointer (0x10) then as a consumer how will I know if a given string field Size is the in-line size or the size of a ref|pointer.

We don't want to say to users "if the string field Size attr = 0x10 then it's a ref|pointer and can be any size, else it's an in-line string of Size char".

**Comment by monkeyman192** [comment]
> What Size attr value will VariableSizeString fields have once converted to string ? My assumption is they will be the size of the ref|pointer i.e. 0x10. I assume they are not stored in-line like fixed length strings, maybe I 'm wrong.

What do you mean by "converted into a string"?
The point of `SizeOf` in this case is to determine how much space the given field takes up within the class. So the VariableSizeString is indeed just 0x10 bytes.
If you want the size of the string once it has actually been read then you'd simply get the length of the value of that class however you normally do in c# (ie `string.Length`)

Maybe another way of thinking about this is that were are getting the size of fields in the class type, not a class instance.

**Comment by cmkushnir** [comment]
Let's say there is a current struct like:
```
struct blah {
    NMSString0x10 field1;
    VariableSizeString field2;
}
```
this will be converted to:
```
struct blah {
    [NMSField(Size = 0x10)]
    string field1;
    [NMSField(Size = 0x10)]
    string field2;
}
```
After the conversion, as a user of mbinc, how will I know that field1 can only hold 0x10 char, whereas field2 can hold any number of char ?

**Comment by monkeyman192** [comment]
> Let's say there is a current struct like:
> 
> ```
> struct blah {
>     NMSString0x10 field1;
>     VariableSizeString field2;
> }
> ```
> 
> this will be converted to:
> 
> ```
> struct blah {
>     [NMSField(Size = 0x10)]
>     string field1;
>     [NMSField(Size = 0x10)]
>     string field2;
> }
> ```
> 
> After the conversion, as a user of mbinc, how will I know that field1 can only hold 0x10 char, whereas field2 can hold any number of char ?

Ok, I think there is some confusion!
This PR doesn't make this change you described above, that will be in a future PR to change the string types to system strings. But also in that change the variable sized string isn't changing. It is staying as is.

**Comment by cmkushnir** [comment]
When I saw:
```
            } else if (field.FieldType.Name == "String") {
                // The length of a string is an attribute.
                size = field.GetCustomAttribute<NMSAttribute>()?.Size ?? 0;
```
I assumed it was in prep for changing NMSString* to string fields w/ a Size attr.  Even if NMSString to string isn't done in this pr I wasn't sure how VariableSizeString would be handled.

I strongly believe all string types, including VariableSizeString, should be converted to string, no exceptions.  As such there should be a solution that supports that.  Otherwise we still end up with the odd case where a user has to use field.Value to get the string.

My orig comment was around how to handle VariableSizeString, and in a more generic sense any other field that may be allocated instead of inline (though not sure there are any).

**Comment by monkeyman192** [comment]
It is in some was prep, however the change was also required here because the size of a NMSString0xXXX class will retain the size attribute for now (as you can see). So this is an interim solution until the changing of string type occurs.
I hadn't thought about the variable sized string before, but I think that maybe should be a discussion we have once I open that PR.
I'll have more of a think on how we can support having variable sized strings as a system string type. I think it will involve a bit of fiddling but I suspect there may be a solution which involves adding another attribute so that we know to (de)serialize it correctly.
Again, I think the entire discussion surrounding that can be done in the future PR for it.

**Comment by monkeyman192** [comment]
@cmkushnir do you have any other review comments for this?
In the interest of not messing anything up I have changed the branch this will be merged into as a new branch which will be parallel to the development branch for the time being until we have all the libmbin related changes merged.

**Comment by cmkushnir** [comment]
Nope, that was all.

**Pull request merged**
