### PR TITLE
[WIP] Change how strings are handled

### PR DESCRIPTION
**Pull request by monkeyman192**
So this is a huge PR since many many files contain strings.
An issue we have which is talked about in #101 is that some strings of length 0x20 are aligned at 0x8, and others are not aligned. It turns out (can't believe after all this time I never noticed it!) that these two cases are distinguished in the exe, so we can know which strings are aligned and which ones aren't.
This PR does the following:
- Replaces all "normal" c# string field types with the size being specified by an attribute with a `NMSString0xABC` field type.
- Changes the serialisation and deserialisation code to handle this change.
- Changes the format of Lists and Arrays of strings to condense them down a bit.
NOTE: This condensation of lists and arrays MAY cause some scripts to break. This may need to be tested or have this option added as not the default and be toggle-able until tools are updated.
tbh, I think that condensing these strings down is a good thing to do as it will actually make scripts that parse exml files simpler I think! (No having to find the NMSString sub-element and then drilling down into that also!)

### CODE REVIEW

**Comment by chrispurnell** [comment]
You have a lot of the aligned 0x20 length strings using the wrong type.  For example MaterialAlternativeId in TkMaterialSampler.
But other than that is looks good.

**Comment by monkeyman192** [comment]
> 
> 
> You have a lot of the aligned 0x20 length strings using the wrong type. For example MaterialAlternativeId in TkMaterialSampler.
> But other than that is looks good.

Yep, this is why it's still a WIP. I only got through about half of the classes that needed to be updated but I put this PR up for initial review and testing. I'll hopefully finish off all the other classes tonight!

**Comment by chrispurnell** [comment]
Lists all look done.  Except RewardCollected in GcSeasonStateData.  This doesn't even look like a list of strings.  It looks like a list of 16bit integers.  But I can't tell for sure as it is always empty.

**Comment by monkeyman192** [comment]
> 
> 
> Lists all look done. Except RewardCollected in GcSeasonStateData. This doesn't even look like a list of strings. It looks like a list of 16bit integers. But I can't tell for sure as it is always empty.

Yeah, as you can see in the comment I am not sure what this is. I think we need some save data to try and figure out what it is. I agree, probably not a string, but the class uses isn't used anywhere else... And it's not another class (or a list of a class) otherwise we'd be able to tell in the exe, so it must be a list of a primitive type...

**Comment by HolterPhylo** [comment]
> > Lists all look done. Except RewardCollected in GcSeasonStateData. This doesn't even look like a list of strings. It looks like a list of 16bit integers. But I can't tell for sure as it is always empty.
> 
> Yeah, as you can see in the comment I am not sure what this is. I think we need some save data to try and figure out what it is. I agree, probably not a string, but the class uses isn't used anywhere else... And it's not another class (or a list of a class) otherwise we'd be able to tell in the exe, so it must be a list of a primitive type...

I list it as Alt_int_0x4_list(void) as it calls this in a while loop

>                              **************************************************************
>                              *                POINTER to EXTERNAL FUNCTION                *
>                              **************************************************************
>                              int __fastcall atoi(char * _Str)
>              int               EAX:4          <RETURN>
>              char *            RCX:8          _Str
>                              80  atoi  <<not bound>>
>                              PTR_atoi_1422c5f10                              XREF[154]:   VertexStream_???:1402f2aaf, 
>                                                                                           VertexStream_???:1402f2c3e, 
>                                                                                           NMS_int_0x4:1402f625e, 
>                                                                                           NMS_int_0x4:1402f6290, 
>                                                                                           NMS_int_0x4_array:1403e26e5, 
>                                                                                           NMS_int_0x4_list:14041f9d1, 
>                                                                                           NMS_int_0x4_list:14041fb71, 
>                                                                                           FUN_1405c7560:1405c7728, 
>                                                                                           FUN_1405c9110:1405c93ab, 
>                                                                                           FUN_1409c50f0:1409c51dc,  more
>  .rdata:1422c5f10 3a 2f 99        addr       API-MS-WIN-CRT-CONVERT-L1-1-0.DLL::atoi
> 

In Decompiled view, "value" _Str is converted to int: 

```
              _Str = (char *)G_global_p(local_58,&DAT_1422e6418);
              if (_Str == (char *)0x0) {
                _Str = (char *)G_global_p(local_58,"value");
              }
                    /* atoi() */
              iVar4 = atoi(_Str);

```

**Comment by chrispurnell** [comment]
If you look at the assembly, the instruction immediately after the call to atoi is a move of ax not eax.  So 16 bit.  Also the address is stores ax at is incremented by 2 each iteration of that loop.

**Comment by chrispurnell** [comment]
VariableSizeString could do with the same format changes.  It would really clean up the language files.
Also I would drop the name attribute on strings in lists of strings.

**Comment by HolterPhylo** [comment]
iVar4 = atoi(_Str);
              *(undefined2 *)(lVar6 + uVar11 * 2) = (short)iVar4;

So that makes it a short then? : 'Alt_short_0x2_list' (or is it 'Alt_ushort_0x2_list')

**Comment by chrispurnell** [comment]
If you look at the companion function to the one you are looking at it passes "%d" to vsprintf and not "%u".  That implies signed.

**Comment by HolterPhylo** [comment]
Thanks, that helps me understand more how it works!
What is that companion function?

**Comment by chrispurnell** [comment]
You are looking at the xml serialization function for that list.  There is also are also xml deserialization function in the exe.  I found them by searching for references to the string containing the field name.  I found 4.  Two were followed by virtual calls I couldn't follow.  The other two were followed, a few instructions later, by calls to the xml serializaion and deserialization functions.
I'm just looking at it again and it uses a move with sign extend, so definitly signed.

**Comment by cmkushnir** [comment]
Since you've decided on this approach, I'd suggest the following changes:

1) Make NMSString0x10 name consistant w/ others.  NMSString0x10 align should be 1 to match others, or name should be changed to NMSString0x10A to match NMSString0x20A which also has align = 8.

2) Make INMSString more .NET friendly, e.g.
<pre>
        // INMSString doesn't need to be an interface, can just be base class (?)
	public class INMSString : NMSTemplate
	{
		public INMSString () : base() { }
		public INMSString ( string STR ) : base() { Value = STR; }

		public string Value { get; set; }  // instead of StringValue method

		public int Size {
			get {
				var attr = this.GetType().GetCustomAttribute(typeof(NMSAttribute)) as NMSAttribute;
				return attr?.Size ?? 0;
			}
		}
		public int Alignment {
			get {
				var attr = this.GetType().GetCustomAttribute(typeof(NMSAttribute)) as NMSAttribute;
				return attr?.Alignment ?? 1;  // default == 1 (or whatever)
			}
		}

		public override string ToString ()  // makes binding to UI elements easier
		{
			return Value;
		}

		public static implicit operator string ( INMSString STR ) => STR.Value;
	//	public static implicit operator INMSString ( string STR ) => new INMSString(STR);
	}

	[NMS(Size = 0x20, Alignment = 0x1)]
	public class NMSString0x20 : INMSString
	{
		public NMSString0x20 () : base() {}
		public NMSString0x20 ( string STR ) : base(STR) {}
		public static implicit operator NMSString0x20 ( string STR ) => new NMSString0x20(STR);
	}

	[NMS(Size = 0x20, Alignment = 0x8)]
	public class NMSString0x20A : INMSString
	{
		public NMSString0x20A () : base() {}
		public NMSString0x20A ( string STR ) : base(STR) {}
		public static implicit operator NMSString0x20A ( string STR ) => new NMSString0x20A(STR);
	}

... and so on for other  NMSString0x* classes.
</pre>
Use:
<pre>
			NMSString0x20  x = "blah";
			NMSString0x20A y = x.Value;  // no auto-conversion possible using just to|from string conversions

			var sx = x.Size;  // 32
			var sy = y.Size;  // 32
			var ax = x.Alignment;  // 1
			var ay = y.Alignment;  // 8

			INMSString z = x;
			var sz = z.Size;  // 32
			var az = z.Alignment;  // 1

			z  = y;
			sz = z.Size;  // 32
			az = z.Alignment;  // 8
</pre>

**Comment by cmkushnir** [comment]
May also want to change VariableSizeString to:
<pre>
	[NMS(Size = 0x10, Alignment = 0x1)]
	public class NMSStringN : INMSString
	{
		public NMSStringN () : base() {}
		public NMSStringN ( string STR ) : base(STR) {}
		public static implicit operator NMSStringN ( string STR ) => new NMSStringN(STR);
	}
</pre>
So that code that uses string compare on class name can just use name.StartsWith("NMSString") to catch all string types.  Only the code to go from dom to binary would need to check if NMSStringN or not to diff 16 meaning inline size vs ref (or whatever purpose size =16 serves for VariableSizeString).

**Comment by monkeyman192** [comment]
@cmkushnir thanks for the detailed response! I'll definitely take in some of those suggestions!
I think I did it as an interface because I was struggling with how to get class inheritance working like you have shown! (c# really isn't my primary language haha!)
making the change from an interface to a class will of course mean other changes to NMSTemplate.cs, but I think it's better to do it like that then as an interface...
WRT the variable size string change. We could do this, but I think for now it's better to keep the name. Could definitely subclass it though.
Maybe in the future if we come up with a new exml format we can change some things, but for now I'd like this PR to keen the exml format EXACTLY the same as it is to introduce no unwanted changes.

For the NMSString0x10 suggestion... I am not so sure about it. I understand the reasoning behind the suggestion, however, the change would be an internal only one. Insofar as the string would never be displayed in the exml as `NMSString0x10A`, like how both `NMSString0x20` and `NMSString0x20A` appear in the exml as `NMSString0x20`. The user doesn't need to know the alignment of stuff, nor do they care, and I think having a difference would only introduce confusion.

**Comment by cmkushnir** [comment]
Hmm, the only change I saw in NMSTemplate was:
valueString = ((NMS.INMSString)value).StringValue();
to
valueString = ((NMS.INMSString)value).Value;
maybe I missed something ...

"Insofar as the string would never be displayed in the exml as NMSString0x10A"
hadn't noticed the custom check to flatten NMSString0x20A to NMSString0x20 on export.  I agree that there is no use-case for anyone at the dom or higher level to know about alignment.  For me class naming consistency is important in API design; that is my focus is on the dom architecture, not maintaining backward compat w/ exml.

**Pull request merged**
