### PR TITLE
Linux build

### PR DESCRIPTION
**Pull request by SplinterGU**
update to current MBINCompiler version

### CODE REVIEW

**Comment by monkeyman192** [comment]
You still need to update the .sh and .bat files, as well as modify the pipeline.yml file before I can run the CI

**Comment by SplinterGU** [comment]
> You still need to update the .sh and .bat files, as well as modify the pipeline.yml file before I can run the CI

But that doesn't affect your pipeline or anything; it will simply create files that you won't publish, but you'll still be able to publish as you have been doing. The Windows release will be visible, and that's it. However, those of us with Linux will be able to compile it without any issues.

**Comment by SplinterGU** [comment]
Anyway, there's no problem. I can continue maintaining my repository for Linux. It's not a big change that I have to make, and I can use it without any worries. So, don't worry about the merge or the pull request.

Thanks anyway!

**Comment by monkeyman192** [comment]
> But that doesn't affect your pipeline or anything; it will simply create files that you won't publish, but you'll still be able to publish as you have been doing. The Windows release will be visible, and that's it. However, those of us with Linux will be able to compile it without any issues.

This DOES affect the pipeline because in it we specify the framework (`dotnet publish libMBIN-DLL -c Release -f net6.0-windows -r win-x64 -o Build/Release/net6/ /nowarn:cs0618`)
This command will fail as it stands because this framework is no longer specific in the .csproj files.

I am happy to add linux build support to this, just want it done the right way :P
It's going to be annoying for you to have to constantly modify stuff every time you want to build.

**Comment by SplinterGU** [comment]
> > But that doesn't affect your pipeline or anything; it will simply create files that you won't publish, but you'll still be able to publish as you have been doing. The Windows release will be visible, and that's it. However, those of us with Linux will be able to compile it without any issues.
> 
> This DOES affect the pipeline because in it we specify the framework (`dotnet publish libMBIN-DLL -c Release -f net6.0-windows -r win-x64 -o Build/Release/net6/ /nowarn:cs0618`) This command will fail as it stands because this framework is no longer specific in the .csproj files.
> 
> I am happy to add linux build support to this, just want it done the right way :P It's going to be annoying for you to have to constantly modify stuff every time you want to build.

I don't understand, my commit doesn't have net6.0-windows, it has net6.0 and net7.0... On the other hand, the csproj files do have those two...

I don't understand why It will fail... the problem is net6.0? I can remove it... I don't understand...

image

**Comment by SplinterGU** [comment]
I compile it with the script and it works... really, I don't understand that you mean...

>> It's going to be annoying for you to have to constantly modify stuff every time you want to build.

nah, no problem with it... it is easy... but well...

**Comment by monkeyman192** [comment]
I ran the CI to hopefully show you what is wrong 😉

**Comment by SplinterGU** [comment]
aahh, need change this...

          dotnet publish libMBIN-DLL -c Release -f net6.0-windows -r win-x64 -o Build/Release/net6/ /nowarn:cs0618
          dotnet publish MBINCompiler -c Release -f net6.0-windows -r win-x64 -o Build/Release/net6/ /nowarn:cs0618
          dotnet publish SaveFileMapping -c Release -f net6.0-windows -r win-x64 -o Build/Release/net6/ /nowarn:cs0618
          dotnet publish libMBIN-DLL -c Release -f net7.0-windows -r win-x64 -o Build/Release/net7/ /nowarn:cs0618
          dotnet publish MBINCompiler -c Release -f net7.0-windows -r win-x64 -o Build/Release/net7/ /nowarn:cs0618


remove -windows... I can do it

**Comment by SplinterGU** [comment]
done! please, try again

**Pull request closed without merging**
